apiVersion: k8s.refunc.io/v1beta3
kind: Xenv
metadata:
  name: nodejs12.x
spec:
  type: lambda
  transport: nats
  poolSize: 1
  container:
    image: refunc/lambda:nodejs12.x
    imagePullPolicy: IfNotPresent
