apiVersion: k8s.refunc.io/v1beta3
kind: Xenv
metadata:
  name: golang1.17
spec:
  type: lambda
  transport: nats
  poolSize: 1
  container:
    image: refunc/lambda:golang1.17
    imagePullPolicy: IfNotPresent
